language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

# Use container-based infrastructure
sudo: false

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install .
  - pip install -r requirements.txt

  # Coverage 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run --omit=langdetect/tests/* -m unittest2 discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then coverage run --omit=langdetect/tests/* -m unittest discover; fi

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pyflakes .| tee >(wc -l)
 - pep8 --statistics --count .
