language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# Use container-based infrastructure
sudo: false
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install .
  - pip install -r requirements.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then unit2 discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then python -m unittest discover; fi
